### ISSUE TITLE
Add Option to Skip Tutorial

### ISSUE THREAD

**Issue by NateSeymour** [InspiranzaDEV/zenenti#42]
# Description
Add "skip" (omitir) button to the tutorial screen to skip the tutorial. [See reference designs in Figma](https://www.figma.com/design/FS3Qcbu6fVLM2gQwAjXWWa/Inspiranza-lo-fi?node-id=0-1&node-type=canvas&t=AcFUZAjkKD19HKZv-0)

# User Story
**As a** user, **I want** the ability to skip the tutorial, **so that** I can view it later if desired.

# Dependencies
- Depends on #41.

**Comment by MichalT106** [comment]
Hi @NateSeymour , can you asign me on this issue? I start work on it.

**Comment by NateSeymour** [comment]
@MichalT106 All yours! Have fun :)

**Comment by MichalT106** [comment]
Hi @NateSeymour , I created the pull request #65 , can you please check it and merge if everithing is okey?

I added a button where, after clicking on it, the playback of the audio from the tutorial will stop and it will redirect the user to the end of the tutorial.

I also added stopping the audio to the continue button in the tutorials, so that when a person jumps to the next part of the tutorial before the end of the audio, so that multiple audios are not played at once.

You can see the results of the changes: ![Video Title](https://youtu.be/Ks07iIrjv_g)

**Comment by MichalT106** [comment]
Hi, @NateSeymour, so the changes are:

- updated the button relevant to figma
- remove of standard HTML elements 
- used tailwind for styling

unfortunately, after a long time, I did not manage to place the button correctly in the upper right corner without disturbing the other objects.

 Well, based on the new changes where I changed button component to add a secondary button, I then used this component in [name].jsx.  In this new implementation of mine, only two files are modified without interfering with global.css or _layout.js for the tutorial view.

Despite the incorrect placement of the button after a long effort, I would like to ask for a review and approval of my implementation #65 , with the bonus of solving the audio stoping problem. 


You can see the results of the changes here: [Video Title](https://www.youtube.com/watch?v=Q9NWdm36dOw)
